### ISSUE TITLE
Company

### ISSUE THREAD

**Issue by Erik-E-Christensen** [D-Multi/Chomper-Basket#2]
Are you planning on creating D-Multi as a real company? I was wondering if you want to maybe subsidize it then you can work independently under cTechstudios but cTechstudios can spread its assets, this means that cTechstudios would own it but it runs on its own, if one fails the other is not affected

**Comment by dguisti** [comment]
No thanks. I am planning on eventually turning it into a real company, but I think I have some time before that is needed. Thanks for the offer though!
